#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    GYRO,           sensorGyro)
#pragma config(Sensor, dgtl1,  LEFT_FLY_QUAD_1, sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  RIGHT_FLY_QUAD_1, sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  INTAKE_SOLENOID, sensorDigitalOut)
#pragma config(Sensor, I2C_1,  LEFT_FLY_IME,   sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  RIGHT_FLY_IME,  sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_3,  FRONT_LEFT_BOT_DRIVE_IME, sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_4,  FRONT_RIGHT_BOT_DRIVE_IME, sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_5,  LIFT_IME,       sensorQuadEncoderOnI2CPort,   , AutoAssign)
#pragma config(Sensor, I2C_6,  INTAKE_IME,     sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           FRONT_LEFT_BOT_DRIVE_MOTOR, tmotorVex393HighSpeed_HBridge, openLoop, driveLeft, encoderPort, I2C_3)
#pragma config(Motor,  port2,           FRONT_LEFT_TOP_DRIVE_MOTOR, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           BACK_LEFT_BOT_DRIVE_MOTOR, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           INTAKE_MOTOR,  tmotorVex393_MC29, openLoop, driveLeft, encoderPort, I2C_6)
#pragma config(Motor,  port5,           LEFT_FLY_MOTOR, tmotorVex393HighSpeed_MC29, openLoop, driveLeft, encoderPort, I2C_2)
#pragma config(Motor,  port6,           RIGHT_FLY_MOTOR, tmotorVex393HighSpeed_MC29, openLoop, driveRight, encoderPort, I2C_1)
#pragma config(Motor,  port7,           LIFT_MOTOR,    tmotorVex393_MC29, openLoop, driveRight, encoderPort, I2C_5)
#pragma config(Motor,  port8,           BACK_RIGHT_DRIVE_MOTOR, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           FRONT_RIGHT_TOP_DRIVE_MOTOR, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          FRONT_RIGHT_BOT_DRIVE_MOTOR, tmotorVex393HighSpeed_HBridge, openLoop, driveRight, encoderPort, I2C_4)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "PidLib.c"
#include "Autonomous.c"

#pragma platform(VEX)
//COMP DUR SETTINGS
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!
#include "Usercontrol.c"

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
	// Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{

	AutonControlInit();  // Remove this function call once you have "real" code.
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{

	UserControlInit();  // Remove this function call once you have "real" code.
}
